# Site settings
title: Anthony Rios
email: anthonymrios@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://anthonymrios.net" # the base hostname & protocol for your site
twitter_username: anthonymrios
github_username: anthonymrios
linkedin_username: anthonyrios0

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Ph.D. Candidate"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
