# Site settings
title: Anthony Rios
email: anthony.rios@utsa.edu
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://anthonymrios.net" # the base hostname & protocol for your site
twitter_username: https://twitter.com/anthonymrios
github_username: https://github.com
linkedin_username: https://www.linkedin.com/in/anthonyrios0/

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Assistant Professor"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
