# Site settings
title: Anthony Rios blog
email: anthonymrios@gmail.com
description: > # this means to ignore newlines until "baseurl:"
   Pretending to be a computer scientist.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://anthonyrios.net" # the base hostname & protocol for your site
twitter_username: anthonymrios
github_username: anthonymrios

# Build settings
markdown: kramdown
